### ISSUE TITLE
Support persistent cache

### ISSUE THREAD

**Issue by mvhirsch** [webpack-contrib/grunt-webpack#241]
Webpack 5 introduced persistent (filesystem based) cache, which speeds up build performance in CI by ... a lot.
This plugin forces my setting always to be `false`, rendering my cache setup useless in CI.

https://webpack.js.org/guides/build-performance/#persistent-cache

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

```js
{
    options: {
        cache: {
            type: 'filesystem',
            cacheDirectory: path.resolve('<%= paths.cache %>/webpack')
        }
    }
}
```

### Expected Behavior

A cached output on destination

### Current Behavior

No output

### Your Environment

| software         | version
| ---------------- | -------
| webpack          | 5.89.0
| grunt-webpack    | 6.0.0
| grunt            | 1.5.3
| node             | 14.21.3
| npm              | 6.14.18
| Operating System | Fedora 39 - 6.8.9-200.fc39.x86_64 GNU/Linux

**Comment by mvhirsch** [comment]
Looks like unless I _want_ to `watch: true` (on build servers I usually don't want to watch ...) it's impossible to use build-cache using this module.

https://github.com/webpack-contrib/grunt-webpack/blob/080fa7d15403de9e176085082917bde527d4ca60/src/options/WebpackOptionHelper.js#L22-L26

**Comment by danez** [comment]
After diving into webpack 5 and 4 and comparing the cache plugins to figure out why we had this logic here, it turned out we do not need it anymore. :)

In webpack verion 4 special code was necessary to make the cache work with grunts multi-target system. The cache plugin in version 4 was storing one global cache for all compilers it was attached to. In webpack 5 this is not necessary anymore as the cache now creates a new storage for each compiler.
