### ISSUE TITLE
template strings do not process in Plugins

### ISSUE THREAD

**Issue by iDVB** [webpack-contrib/grunt-webpack#53]
This..

``` javascript
          new HtmlWebpackPlugin({
            gitHash: '<%= gitinfo.local.branch.current.shortSHA %>', 
            template: 'index.html', // Load a custom template 
            inject: false
          })
```

results in this html...

``` html
 <div id="voterapp" data-githash="&lt;%= gitinfo.local.branch.current.shortSHA %&gt;"></div>
```

**Comment by MichaelSitter** [comment]
@iDVB the issue name is misleading; these are called template strings in the grunt documentation: http://gruntjs.com/api/grunt.template

But yeah, I'm having the same problem. Config settings work file because they are actually parsed by grunt and compiled, but if you think about it the webpack plugins have no idea they are being consumed by grunt. So the template replacements would never happen.

**Comment by nwoltman** [comment]
This is not a bug. As @MichaelSitter mentioned, grunt does not have access to anything passed to a plugin's constructor, so it can't process template strings passed to plugins.

If you really want to use grunt's template strings in this manner, here is a potential workaround:

```js
new HtmlWebpackPlugin({
  get gitHash() {
    return grunt.template.process('<%= gitinfo.local.branch.current.shortSHA %>')
  },
  template: 'index.html', // Load a custom template 
  inject: false
})
```

**Comment by knightcode** [comment]
Adding another example here since this issue was the solution I was looking for:

```js
new webpack.DefinePlugin({
  "process.env": {
   get DEPLOY_VERSION() {
      return grunt.template.process("'?v=<%= DEPLOY_VERSION %>'")
    }
  }
})
```

I'm able to call `grunt.config("DEPLOY_VERSION", val)` from another grunt task each iteration of `grunt watch` to bust my browser cache.
